const CARDS = {
'2C': './src/img/cards/2C.png',
'3C': './src/img/cards/3C.png',
'4C': './src/img/cards/4C.png',
'5C': './src/img/cards/5C.png',
'6C': './src/img/cards/6C.png',
'7C': './src/img/cards/7C.png',
'8C': './src/img/cards/8C.png',
'9C': './src/img/cards/9C.png',
'10C': './src/img/cards/10C.png',
'JC': './src/img/cards/JC.png',
'QC': './src/img/cards/QC.png',
'KC': './src/img/cards/KC.png',
'AC': './src/img/cards/AC.png',
'2D': './src/img/cards/2D.png',
'3D': './src/img/cards/3D.png',
'4D': './src/img/cards/4D.png',
'5D': './src/img/cards/5D.png',
'6D': './src/img/cards/6D.png',
'7D': './src/img/cards/7D.png',
'8D': './src/img/cards/8D.png',
'9D': './src/img/cards/9D.png',
'10D': './src/img/cards/10D.png',
'JD': './src/img/cards/JD.png',
'QD': './src/img/cards/QD.png',
'KD': './src/img/cards/KD.png',
'AD': './src/img/cards/AD.png',
'2H': './src/img/cards/2H.png',
'3H': './src/img/cards/3H.png',
'4H': './src/img/cards/4H.png',
'5H': './src/img/cards/5H.png',
'6H': './src/img/cards/6H.png',
'7H': './src/img/cards/7H.png',
'8H': './src/img/cards/8H.png',
'9H': './src/img/cards/9H.png',
'10H': './src/img/cards/10H.png',
'JH': './src/img/cards/JH.png',
'QH': './src/img/cards/QH.png',
'KH': './src/img/cards/KH.png',
'AH': './src/img/cards/AH.png',
'2S': './src/img/cards/2S.png',
'3S': './src/img/cards/3S.png',
'4S': './src/img/cards/4S.png',
'5S': './src/img/cards/5S.png',
'6S': './src/img/cards/6S.png',
'7S': './src/img/cards/7S.png',
'8S': './src/img/cards/8S.png',
'9S': './src/img/cards/9S.png',
'10S': './src/img/cards/10S.png',
'JS': './src/img/cards/JS.png',
'QS': './src/img/cards/QS.png',
'KS': './src/img/cards/KS.png',
'AS': './src/img/cards/AS.png',


}

export default CARDS;